const {test, expect} = require('@playwright/test');


//Generated by Codegen 
//Refractored to use POM structure
test('Login to CheckOut Test', async ({ page }) => {
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.login('standard_user', 'secret_sauce');
    const inventoryPage = new InventoryPage(page);
    await inventoryPage.addItemToCart('sauce-labs-backpack');
    await inventoryPage.goToCart();
    const cartPage = new CartPage(page);
    await cartPage.validateItemInCart('Sauce Labs Backpack');
    await cartPage.proceedToCheckout();
    const checkoutPage = new CheckoutPage(page);
    await checkoutPage.fillCheckoutInformation('User', 'UserLastName', '2341');
    await checkoutPage.finishCheckout();
    const checkoutCompletePage = new CheckoutCompletePage(page);
    await checkoutCompletePage.validateOrderCompletion();
});

