import { test, expect } from '@playwright/test';
import { LogInPage } from '../pages/LogInPages.js';
import { InventoryPage } from '../pages/InventoryPages.js';
import { CartPage } from '../pages/CartPages.js';
import { CheckOutPage } from '../pages/CheckOutPages.js';


//Generated by Codegen 
//Refractored to use POM structure
test('Login to CheckOut Test', async ({ page }) => {
    const loginPage = new LogInPage(page);
    await loginPage.goto();
    await loginPage.login('standard_user', 'secret_sauce');
    const inventoryPage = new InventoryPage(page);
    await inventoryPage.addItemToCart();
    await inventoryPage.goToCart();
    const cartPage = new CartPage(page);
    await expect(await cartPage.isItemInCart('Sauce Labs Backpack')).toBeTruthy();
    await cartPage.proceedToCheckout();
    const checkoutPage = new CheckOutPage(page);
    await checkoutPage.fillShippingInformation('User', 'UserLastName', '2341');
    await checkoutPage.continueCheckout();
    await checkoutPage.finishCheckout();
    await expect(page).toHaveURL('https://www.saucedemo.com/checkout-complete.html');
});

